name: Parasoft Scan

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ "main" ]

jobs:
  parasoft_scan:
    runs-on: ubuntu-latest
    outputs:
      s1_count: ${{ steps.parse_issues.outputs.s1 }}
      s2_count: ${{ steps.parse_issues.outputs.s2 }}
      s3_count: ${{ steps.parse_issues.outputs.s3 }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate Parasoft Scan (Generate Dummy Data)
        run: |
          echo "S1=5" >> $GITHUB_ENV
          echo "S2=12" >> $GITHUB_ENV
          echo "S3=20" >> $GITHUB_ENV
          echo "S4=50" >> $GITHUB_ENV

      - name: Parse Issue Counts
        id: parse_issues
        run: |
          echo "s1=${{ env.S1 }}" >> $GITHUB_OUTPUT
          echo "s2=${{ env.S2 }}" >> $GITHUB_OUTPUT
          echo "s3=${{ env.S3 }}" >> $GITHUB_OUTPUT
          echo "s4=${{ env.S3 }}" >> $GITHUB_OUTPUT

      # ------------------ GitHub Actions Summary ------------------
      - name: Update GitHub Actions Summary
        run: |
          echo "### 🚀 Parasoft Scan Results" >> $GITHUB_STEP_SUMMARY
          echo ""
          echo "![Critical](https://img.shields.io/badge/Critical-${{ steps.parse_issues.outputs.s1 }}-red)" \
          "![High](https://img.shields.io/badge/High-${{ steps.parse_issues.outputs.s2 }}-orange)" \
          "![Medium](https://img.shields.io/badge/Medium-${{ steps.parse_issues.outputs.s3 }}-yellow)" \
          "![Low](https://img.shields.io/badge/Low-${{ steps.parse_issues.outputs.s4 }}-yellow)" >> $GITHUB_STEP_SUMMARY

   
